import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import express from "express";

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Global CORS configurations required by Claude web client
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "https://claude.ai");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  if (req.method === "OPTIONS") return res.sendStatus(200);
  next();
});

// Configuration variables
const HOST_URL = process.env.HOST_URL || "https://railway.app"; 
const MOCK_TOKEN = "bypass_token_secure_autopilot_123456";
const MOCK_CLIENT_ID = "claude_web_client_mock_id";
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

// ==========================================
// 1. CLAUDE.AI OAUTH BYPASS & DISCOVERY LAYER
// ==========================================

// Step A: Claude checks features your server supports
app.get("/.well-known/oauth-authorization-server", (req, res) => {
  res.json({
    issuer: HOST_URL,
    authorization_endpoint: `${HOST_URL}/oauth/authorize`,
    token_endpoint: `${HOST_URL}/oauth/token`,
    registration_endpoint: `${HOST_URL}/oauth/register`,
    response_types_supported: ["code"],
    grant_types_supported: ["authorization_code", "urn:ietf:params:oauth:grant-type:token-exchange"],
    token_endpoint_auth_methods_supported: ["none"],
    scopes_supported: ["mcp"],
    code_challenge_methods_supported: ["S256"]
  });
});

// Step B: Claude performs Dynamic Client Registration (DCR)
app.post("/oauth/register", (req, res) => {
  const clientName = req.body.client_name || "Claude Web Client";
  const redirectUris = req.body.redirect_uris || ["https://claude.ai"];

  res.status(201).json({
    client_id: MOCK_CLIENT_ID,
    client_id_issued_at: Math.floor(Date.now() / 1000),
    redirect_uris: redirectUris,
    token_endpoint_auth_method: "none",
    client_name: clientName
  });
});

// Step C: Claude opens auth redirect loop. We immediately auto-approve.
app.get("/oauth/authorize", (req, res) => {
  const { redirect_uri, state } = req.query;
  if (!redirect_uri) return res.status(400).send("Missing redirect_uri parameter.");
  const dummyAuthCode = "mock_code_" + Math.random().toString(36).substring(7);
  res.redirect(`${redirect_uri}?code=${dummyAuthCode}&state=${encodeURIComponent(state)}`);
});

// Step D: Claude exchanges its code for a Bearer token
app.post("/oauth/token", (req, res) => {
  res.json({
    access_token: MOCK_TOKEN,
    token_type: "Bearer",
    expires_in: 3600
  });
});

// ==========================================
// 2. MODEL CONTEXT PROTOCOL LAYER
// ==========================================

function createServer() {
  const server = new Server(
    { name: "autopilot-controller", version: "1.0.0" },
    { capabilities: { tools: {} } }
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => {
    return {
      tools: [{
        name: "evaluate_current_schema",
        description: "Audits SharePoint and OneDrive spreadsheets to check for empty cell data failures.",
        inputSchema: {
          type: "object",
          properties: { fileName: { type: "string" } },
          required: ["fileName"]
        }
      }]
    };
  });

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    if (request.params.name === "evaluate_current_schema") {
      const args = request.params.arguments || {};
      const fName = args.fileName || "Unknown";

      // 1. Guard check: make sure the token exists before running your tool logic
      if (!GITHUB_TOKEN) {
        return {
          content: [{
            type: "text",
            text: "[MCP ERROR] Configuration missing: GITHUB_TOKEN environment variable is not set on Railway."
          }]
        };
      }

      // 2. Your tool logic using the token (e.g., calling the GitHub API)
      // Example header setup for a fetch request:
      // const headers = { 'Authorization': `token ${GITHUB_TOKEN}` };

      let columnResponse = "['StudentNumber', 'ScanTimestamp', 'SignInStatus', 'Subject']";
      if (fName.includes("Lecturer")) {
        columnResponse = "['SubjectName', 'LecturerEmail']";
      }

      return {
        content: [{
          type: "text",
          text: `[MCP SUCCESS] Authenticated to GitHub. Target file: '${fName}'. Verified Columns: ${columnResponse}.`
        }]
      };
    }
    throw new Error("Tool not found");
  });

  return server;
}

// Secure /mcp route using the generated bypass token
app.post("/mcp", async (req, res) => {
  const authHeader = req.headers.authorization;
  
  if (!authHeader || authHeader !== `Bearer ${MOCK_TOKEN}`) {
    return res.status(401).json({ error: "Unauthorized access to MCP Endpoint" });
  }

  const server = createServer();
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined
  });
  
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`AutoPilot MCP running on port ${PORT}`));
